#! /bin/bash
### BEGIN INIT INFO
# Provides:          autostart-container
# Required-Start:    $remote_fs $syslog dbus
# Required-Stop:     $remote_fs $syslog dbus
# Default-Start:     2 3 4 5
# Default-Stop:	     0 1 6
# Short-Description: Auto-run containers
### END INIT INFO


PATH=/sbin:/usr/sbin:/bin:/usr/bin

do_containers() {
	for container in /etc/container/*/app.lua /etc/container/*.lua ; do
		if [ -f $container ] ; then
			echo $container $1
			timeout --foreground 10s sh -c "${container} $1"
		fi
	done
	return $$
}

case "$1" in
    start)
	do_containers start
	exit 3
        ;;
    restart)
        do_containers restart
        exit 0
        ;;
    stop)
        do_containers stop
        exit 0
        ;;
    clean)
	do_containers clean
	exit 0
	;;
    scbs)
	do_containers scbs
	;;
    *)
        echo "Usage: $0 start|stop|restart|clean" >&2
        exit 3
        ;;
esac
