CC=gcc
CFLAGS=-I.
INSTALL_PATH=/usr/sbin

container: lua/liblua.a defaultlua.o
	$(CC) container.c lua/liblua.a defaultlua.o -o container -ldl -lm

all: container container-src.tar.gz

lua/liblua.a:
	$(MAKE) -C lua linux

defaultlua.o:
	ld -r -b binary -o defaultlua.o container.lua

clean:
	-rm -f defaultlua.o container container-src.tar.gz
	-for script in examples/.*.lua; do \
		if [ -f /usr/sbin/container ]; then \
			(kill -s 9 `cat $$script/.pid`); \
			(cho rm -rf $$script); \
		fi \
		done
	$(MAKE) -C lua clean

install: container
	cp container ${INSTALL_PATH}

src: container-src.tar.gz

container-src.tar.gz:
	tar -zcf container-src.tar.gz --transform 's,^,container/,' container.c container.lua examples/*.lua lua/*.c lua/*.h Makefile lua/Makefile
